--------------------------------------------------------
--  File created - Tuesday-November-21-2023   
--------------------------------------------------------
REM INSERTING into FC143.STTM_IZABORA_EXPOSURE
SET DEFINE OFF;
Insert into FC143.STTM_IZABORA_EXPOSURE (EXPOSURE_CATEGORY) values ('Fourth');
Insert into FC143.STTM_IZABORA_EXPOSURE (EXPOSURE_CATEGORY) values ('First');
Insert into FC143.STTM_IZABORA_EXPOSURE (EXPOSURE_CATEGORY) values ('Second');
Insert into FC143.STTM_IZABORA_EXPOSURE (EXPOSURE_CATEGORY) values ('Third');
