--------------------------------------------------------
--  File created - Tuesday-November-21-2023   
--------------------------------------------------------
REM INSERTING into FC143.STTM_BOR22_PRODUCT
SET DEFINE OFF;
Insert into FC143.STTM_BOR22_PRODUCT (PRODUCT_CODE,CAT) values ('ACCO','FIRST');
Insert into FC143.STTM_BOR22_PRODUCT (PRODUCT_CODE,CAT) values ('ACCO','SECOND');
Insert into FC143.STTM_BOR22_PRODUCT (PRODUCT_CODE,CAT) values ('ACCO','THIRD');
Insert into FC143.STTM_BOR22_PRODUCT (PRODUCT_CODE,CAT) values ('AMEX','FIRST');
Insert into FC143.STTM_BOR22_PRODUCT (PRODUCT_CODE,CAT) values ('AMEX','THIRD');
Insert into FC143.STTM_BOR22_PRODUCT (PRODUCT_CODE,CAT) values ('AMMO','FIRST');
Insert into FC143.STTM_BOR22_PRODUCT (PRODUCT_CODE,CAT) values ('AMMO','THIRD');
